---

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/ticketsale_db
        username: ticketsale
        password: t1ck3t_s4l3
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true

...